ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirector
from django.conf.urls.static import static
from ChatApp import settings
from chat_app import views as chat_views


urlpatterns = [
    path('', redirector),
    path('admin/', admin.site.urls),
    path('chat/', include('chat_app.urls')),
    path('account/', include('account_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('video-call/<slug:room_slug>', chat_views.video_call, name='video_call'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat_app/urls.py
from django.urls import path
from . import views


app_name = 'chat'
urlpatterns = [
    path('lobby', views.LobbyView.as_view(), name='lobby'),
    path('room/<slug:room_slug>', views.RoomView.as_view(), name='room'),
    path('create', views.create_room_view, name='create-room'),
    path('join-room', views.join_room, name='join-room'),
    path('remove-room', views.remove_room, name='remove-room'),
]

chat_app/models.py
from datetime import datetime
from django.db import models
from django.utils.text import slugify
from account_app.models import User


class ChatRoom(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='room_creator')
    room_name = models.CharField(max_length=50, unique=True)
    members = models.ManyToManyField(User, related_name='rooms')
    room_image = models.ImageField(upload_to='room-image', blank=True, null=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.room_name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.room_name)
        super(ChatRoom, self).save()


class Message(models.Model):
    chat_room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, null=True, related_name='messages')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(blank=True,  null=True, upload_to='image-message')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username


STATUS_LIST = {
    0: 'Contacting',
    1: 'Not Available',
    2: 'Accepted',
    3: 'Rejected',
    4: 'Busy',
    5: 'Processing',
    6: 'Ended',
}


class VideoCall(models.Model):
    caller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='caller')
    callee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='callee')
    status = models.PositiveSmallIntegerField(default=0)
    date_started = models.DateTimeField(default=datetime.now())
    date_ended = models.DateTimeField(default=datetime.now())
    date_created = models.DateTimeField(auto_now_add=True)

    @property
    def status_name(self):
        return STATUS_LIST[self.status]

    @property
    def duration(self):
        return self.date_ended - self.date_started

ChatApp/views.py
from django.shortcuts import redirect


def redirector(request):
    if request.user.is_authenticated:
        return redirect('chat:lobby')
    else:
        return redirect('account:login')

chat_app/views.py
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.safestring import mark_safe
import json
from .models import ChatRoom, Message, VideoCall
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.contrib.auth.decorators import login_required


class LobbyView(LoginRequiredMixin, View):
    login_url = 'account:login'

    def get(self, request):
        user = request.user
        chat_rooms = ChatRoom.objects.filter(members=user).prefetch_related('members')
        return render(request, 'chat_app/lobby.html', {'chat_rooms': chat_rooms})

    def post(self, request):
        # post method for checking room existence and user - used for search room feature
        room_name = request.POST.get('room_name', None)
        user = request.user
        if room_name and user:
            try:
                chat_room = ChatRoom.objects.get(room_name=room_name)
                if user in chat_room.members.all():
                    return JsonResponse({'status': 409})
                else:
                    return JsonResponse({"status": 200})
            except ChatRoom.DoesNotExist:
                return JsonResponse({"status": 404})
        return JsonResponse({'status': 400})


class RoomView(LoginRequiredMixin, View):
    login_url = 'account:login'

    def get(self, request, room_slug):
        username = request.user.username
        try:
            chat_model = ChatRoom.objects.get(slug=room_slug)
            message_model = Message.objects.filter(chat_room=chat_model).select_related('chat_room', 'author')
            context = {
                'message_model': message_model,
                'chat_model': chat_model,
                'room_name': chat_model.room_name,
                'username': mark_safe(json.dumps(username)),
            }
            return render(request, 'chat_app/room.html', context=context)
        except ChatRoom.DoesNotExist:
            raise ValidationError('Room does not exist, Maybe it was deleted by its creator')


@login_required(login_url='account:login')
@csrf_protect
def create_room_view(request):
    if request.method == 'POST':
        user = request.user
        room_name = request.POST.get('room_name', None)
        if not room_name:
            return JsonResponse({'status': 400})
        elif ChatRoom.objects.filter(room_name=room_name).exists():
            return JsonResponse({'status': 409})
        else:
            created_room = ChatRoom.objects.create(room_name=room_name, creator=user)
            created_room.members.add(user)
            return JsonResponse({'status': 200})


@login_required(login_url='account:login')
@csrf_protect
def join_room(request):
    if request.method == 'POST':
        user = request.user
        room_name = request.POST.get('room_name', None)
        if user and room_name:
            channel_layer = get_channel_layer()
            room_group_name = f'chat_{room_name}'
            async_to_sync(channel_layer.group_send)(
                room_group_name, {
                    'type': 'chat_message',
                    'command': 'info',
                    'content': {
                        'type': 'join',
                        'message': f'{user.username} joined the room',
                        'first_name': user.first_name,
                        'last_name': user.last_name,
                        'username': user.username,
                    },
                }
            )
            room = ChatRoom.objects.get(room_name=room_name)
            room.members.add(user)
            return JsonResponse({'status': 200})
    return JsonResponse({'status': 400})


@login_required(login_url='account:login')
def remove_room(request):
    room_name = request.GET.get('room_name', None)
    user = request.user
    room_group_name = f'chat_{room_name}'
    chat_room = ChatRoom.objects.get(room_name=room_name)
    if room_name and user:
        if user == chat_room.creator:
            channel_layer = get_channel_layer()
            async_to_sync(channel_layer.group_send)(
                room_group_name, {
                    'type': 'chat_message',
                    'command': 'info',
                    'content': {'type': 'delete', 'message': 'Creator delete the room'},
                }
            )
            chat_room.delete()
        else:
            channel_layer = get_channel_layer()
            async_to_sync(channel_layer.group_send)(
                room_group_name, {
                    'type': 'chat_message',
                    'command': 'info',
                    'content': {
                        'type': 'left',
                        'message': f'{user.username} left the room',
                        'username': user.username,
                    },
                }
            )
            chat_room.members.remove(user)
        return JsonResponse({'status': 200})
    return JsonResponse({'status': 400})


@login_required(login_url='account:login')
def video_call(request, room_slug):
    user = request.user
    chat_room_name = ChatRoom.objects.get(slug=room_slug).room_name
    call_logs = VideoCall.objects.filter(Q(callee_id=user.id) | Q(caller_id=user.id)).order_by('-date_created')[:5]
    return render(request, 'chat_app/video_call.html', {
        'call_logs': call_logs,
        'room_name': mark_safe(json.dumps(chat_room_name)),
    })

chat_app/templates/chat_app/lobby.html
{% extends 'templates/base.html' %}
{% load static %}
{% block main %}
    <div class="col-md-4 col-xl-3 chat">
        <div class="card mb-sm-3 mb-md-0 contacts_card">

            <div class="card-header">
                <div class="input-group">
                    <input type="text" placeholder="Search..." id="searchInput" class="form-control search">
                    <div class="input-group-prepend">
                        <span class="input-group-text search_btn"><i class="fas fa-search"></i></span>
                    </div>
                </div>
            </div>

            {% if chat_rooms %}
                <div class="card-body contacts_body">
                    <ul class="contacts">
                        {% for room in chat_rooms %}
                            <li class="d-flex justify-content-between">
                                <a href="{% url 'chat:room' room.slug %}" class="rooms" id="{{ room.room_name }}">
                                    <div class="d-flex bd-highlight">
                                    {% with memeberNum=room.members.count %}
                                        <div class="img_cont">
                                            {% if room.room_image %}
                                                <img src="{{ room.room_image.url }}" class="rounded-circle user_img" alt="Icon">
                                            {% else %}
                                                <img src="{% static 'chat-icon.png' %}" class="rounded-circle user_img" alt="Icon">
                                            {% endif %}
                                                {% if memeberNum > 1 %}
                                                    <span class="online_icon"></span>
                                                {% else %}
                                                    <span class="offline"></span>
                                                {% endif %}
                                        </div>
                                        <div class="user_info">
                                            <span>{{ room.room_name.capitalize }}</span>
                                                {% if memeberNum > 1 %}
                                                    <p>{{ memeberNum }} Members</p>
                                                {% else %}
                                                    <p >{{ memeberNum }} Member</p>
                                                {% endif %}
                                        </div>
                                    {% endwith %}
                                    </div>
                                </a>
                                <a href="#" onclick="removeRoom('{{ room.room_name }}', '{{ room.creator.username }}')"
                                   class="d-flex flex-column justify-content-center text-danger mr-3"
                                   style="font-size: larger">
                                    <i class="fas fa-minus"></i>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <div class="card-body contacts_body d-flex justify-content-center" style="align-items: center">
                    <div class="d-flex flex-column text-center">
                        <span class="text-light font-weight-bold" style="font-size: larger">No Room exists</span>
                        <span class="text-light">Search for a Room or Create a new Room</span>
                    </div>
                </div>
            {% endif %}
            <div class="card-footer text-center">
                <a href="#" class="text-warning" id="createRoom">Create new Room<i class="fas fa-plus"></i></a>
            </div>
        </div>
    </div>

<script>
    // ----------CREATE ROOM
    let createRoomElement = document.getElementById('createRoom');
    createRoomElement.addEventListener('click', event => {
        event.preventDefault();
        Swal.fire({
            title: 'Enter your Room name',
            input: 'text',
            inputAttributes: {
                autocapitalize: 'off',
                required: true,
            },
            showCancelButton: true,
            confirmButtonText: 'Create',
            showLoaderOnConfirm: true,
            preConfirm: (name) => {
                $.ajax({
                    url: '{% url 'chat:create-room' %}',
                    type: 'POST',
                    data: {
                        'room_name': name,
                    },
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                    },
                    success: function (response) {
                        if (response.status === 200) {
                            Swal.fire({
                                position: 'top-start',
                                icon: 'success',
                                title: 'Your new room has been created',
                                showConfirmButton: false,
                                timer: 1500
                            }).then(() => {
                                window.location.reload()
                            })
                        } else if (response.status === 409) {
                            Swal.fire({
                                icon: 'error',
                                title: 'Room Exists',
                                text: 'Room with this name exists. You can search and join the room',
                                confirmButtonColor: '#3085d6',
                            });
                        } else if (response.status === 400) {
                            Swal.fire('Something went wrong, Room name didnt received')
                        }
                    },
                    error: function (error) {
                        Swal.fire({
                            icon: 'error',
                            title: error.code,
                            text: 'Service encountered an error. Please try again. If the error is not resolved, contact support',
                            confirmButtonColor: '#3085d6',
                        })
                        console.log(error)
                    }
                })
            },
            allowOutsideClick: () => !Swal.isLoading()
        })
    });

    // ----------SEARCH ROOM
    let searchInput = document.getElementById('searchInput');
    let searchIcon = document.querySelector('.input-group .search_btn');
    searchInput.addEventListener('keypress', event => {
        if (event.key === 'Enter') {
            searchRoom();
        }
    });
    searchIcon.addEventListener('click', searchRoom);

    function searchRoom() {
        let roomName = searchInput.value;
        if (roomName) {
            $.ajax({
                url: '{% url 'chat:lobby' %}',
                type: 'POST',
                data: {
                    'room_name': roomName,
                },
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                },
                success: function (response) {
                    if (response.status === 400) {
                        showSearchInputError();
                    } else if (response.status === 404) {
                        Swal.fire({
                            icon: 'info',
                            text: 'There is no room with this name',
                            confirmButtonColor: '#3085d6',
                        });
                        clearSearchInput();
                    } else if (response.status === 409) {
                        let room = document.getElementById(`${roomName}`);
                        clearSearchInput();
                        room.click();
                    } else if (response.status === 200) {
                        Swal.fire({
                            title: 'Do you want to join?',
                            text: `Room ${roomName} exists, Do you wanna join?`,
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Yes, Join!'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                $.ajax({
                                    url: '{% url "chat:join-room" %}',
                                    type: 'POST',
                                    data: {
                                        'room_name': roomName,
                                    },
                                    beforeSend: function (xhr) {
                                        xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                                    },
                                    success: function (response) {
                                        if (response.status === 200) {
                                            window.location.reload();
                                            clearSearchInput();
                                        } else if (response.status === 400) {
                                            Swal.fire({
                                                text: 'Somethon went Wrong, try again!',
                                                confirmButtonColor: '#3085d6',
                                            });
                                            clearSearchInput();
                                        }
                                    },
                                    error: function (error) {
                                        Swal.fire({
                                            icon: 'error',
                                            title: error.code,
                                            text: 'Service encountered an error. Please try again. If the error is not resolved, contact support',
                                            confirmButtonColor: '#3085d6',
                                        });
                                        clearSearchInput();
                                        console.log(error)
                                    },
                                })
                            } else {
                                clearSearchInput()
                            }
                        })
                    }
                },
                error: function (error) {
                    Swal.fire({
                        icon: 'error',
                        title: error.code,
                        text: 'Service encountered an error. Please try again. If the error is not resolved, contact support',
                        confirmButtonColor: '#3085d6',
                    });
                    clearSearchInput();
                    console.log(error)
                },
            })
        } else {
            showSearchInputError();
        }
    }

    function showSearchInputError() {
        let inputGroup = searchInput.parentElement;
        inputGroup.style.border = '2px solid red';
        inputGroup.style.borderRadius = '17px';
    }

    function clearSearchInput() {
        searchInput.value = '';
        searchInput.focus();
    }

    // ----------REMOVE ROOM
    function removeRoom(roomName, roomCreator) {
        let text;
        let user = '{{ request.user.username }}';
        if (roomCreator === user){
            text = `Do you want to delete ${roomName} room ?`
        } else {
            text = `Do you want to exit ${roomName} room ?`;
        }
        Swal.fire({
            title: 'Are you sure ?',
            text: text,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, Exit!',
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '{% url "chat:remove-room" %}',
                    data: {
                        'room_name': roomName
                    },
                    success: function (response) {
                        if (response.status === 200) {
                            window.location.reload();
                        } else if (response.status === 400) {
                            Swal.fire({
                                text: 'Somethon went Wrong, try again!',
                                confirmButtonColor: '#3085d6',
                            });
                        }
                    },
                    error: function (error) {
                        Swal.fire({
                            icon: 'error',
                            title: error.code,
                            text: 'Service encountered an error. Please try again. If the error is not resolved, contact support',
                            confirmButtonColor: '#3085d6',
                        });
                        console.log(error)
                    }
                })
            }
        })
    }
</script>
{% endblock %}